apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/auth-depl.yaml
      - infra/k8s/auth-mongo-depl.yaml
      - infra/k8s/tickets-depl.yaml
      - infra/k8s/tickets-mongo-depl.yaml
      - infra/k8s/orders-depl.yaml
      - infra/k8s/orders-mongo-depl.yaml
      - infra/k8s/expiration-depl.yaml
      - infra/k8s/expiration-redis-depl.yaml
      - infra/k8s/payments-depl.yaml
      - infra/k8s/payments-mongo-depl.yaml
      - infra/k8s/nats-depl.yaml
      - infra/k8s/client-depl.yaml
      - infra/k8s/ingress-srv.yaml
build:
  local:
    push: false
  artifacts:
    - image: villagrat/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: villagrat/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: villagrat/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: villagrat/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: villagrat/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: villagrat/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
